# Generated by Django 6.1.1 on 2026-09-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_alter_booking_options_alter_repairjob_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
