# Generated by Django 6.1.1 on 2026-09-17 16:34

from django.db import migrations, models


DEFAULT_ROLES = (
    {
        "code": "ADMIN",
        "name": "Administrator",
        "in_customers": False,
        "in_staff": True,
        "in_technicians": False,
        "default_position": "Administrator",
        "default_department": "Office",
        "sort_order": 1,
    },
    {
        "code": "MANAGER",
        "name": "Manager",
        "in_customers": False,
        "in_staff": True,
        "in_technicians": False,
        "default_position": "Manager",
        "default_department": "Office",
        "sort_order": 2,
    },
    {
        "code": "RECEPTIONIST",
        "name": "Receptionist",
        "in_customers": False,
        "in_staff": True,
        "in_technicians": False,
        "default_position": "Front desk",
        "default_department": "Reception",
        "sort_order": 3,
    },
    {
        "code": "MECHANIC",
        "name": "Mechanic",
        "in_customers": False,
        "in_staff": True,
        "in_technicians": True,
        "default_position": "Mechanic",
        "default_department": "Workshop",
        "sort_order": 4,
    },
    {
        "code": "CASHIER",
        "name": "Cashier",
        "in_customers": False,
        "in_staff": True,
        "in_technicians": False,
        "default_position": "Cashier",
        "default_department": "Finance",
        "sort_order": 5,
    },
    {
        "code": "CUSTOMER",
        "name": "Customer",
        "in_customers": True,
        "in_staff": False,
        "in_technicians": False,
        "default_position": "",
        "default_department": "",
        "sort_order": 6,
    },
)


def seed_roles_and_sync(apps, schema_editor):
    Role = apps.get_model("django_app", "Role")
    User = apps.get_model("django_app", "User")
    Customer = apps.get_model("django_app", "Customer")
    Staff = apps.get_model("django_app", "Staff")
    Mechanic = apps.get_model("django_app", "Mechanic")

    for item in DEFAULT_ROLES:
        Role.objects.get_or_create(
            code=item["code"],
            defaults={key: value for key, value in item.items() if key != "code"},
        )

    roles = {row.code: row for row in Role.objects.all()}
    for user in User.objects.all():
        role = roles.get(user.role)
        in_customers = bool(role and role.in_customers)
        in_staff = bool(role and role.in_staff)
        in_technicians = bool(role and role.in_technicians)
        full_name = f"{user.first_name} {user.last_name}".strip() or user.username
        should_staff = in_staff or in_technicians or bool(user.is_superuser)
        if user.is_staff != should_staff:
            User.objects.filter(pk=user.pk).update(is_staff=should_staff)

        if in_customers:
            Customer.objects.get_or_create(
                user_id=user.id,
                defaults={
                    "name": full_name,
                    "email": user.email or f"{user.username}@carsv.local",
                    "phone": user.phone or "",
                    "photo": user.photo or "",
                    "status": user.status,
                },
            )
        else:
            leftover = Customer.objects.filter(user_id=user.id).first()
            if leftover:
                has_history = (
                    leftover.vehicles.exists()
                    or leftover.bookings.exists()
                    or leftover.repair_jobs.exists()
                    or leftover.invoices.exists()
                    or leftover.payments.exists()
                )
                if not has_history:
                    leftover.delete()

        if in_staff:
            Staff.objects.get_or_create(
                user_id=user.id,
                defaults={
                    "department": user.department,
                    "position": user.position,
                    "status": user.status,
                },
            )
        else:
            Staff.objects.filter(user_id=user.id).delete()

        if in_technicians:
            Mechanic.objects.get_or_create(
                user_id=user.id,
                defaults={"status": user.status, "available": True},
            )
        else:
            Mechanic.objects.filter(user_id=user.id).delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0007_sync_user_profile_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True)),
                ("in_customers", models.BooleanField(default=False, verbose_name="show in customers")),
                ("in_staff", models.BooleanField(default=False, verbose_name="show in staff")),
                ("in_technicians", models.BooleanField(default=False, verbose_name="show in technicians")),
                ("default_position", models.CharField(blank=True, max_length=80)),
                ("default_department", models.CharField(blank=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.RunPython(seed_roles_and_sync, noop),
    ]
